export const LEFT_ARROW = '-left';
export const RIGHT_ARROW = '-right';
export const MAIN_INFO_BLOCK = '__info-block';
export const DATA_TYPES_KEYS = ['TOTAL_DEATHS', 'TOTAL_RECOVERED', 'TOTAL_CONFIRMED',
  'BY_100K_DEATHS', 'BY_100K_RECOVERED', 'BY_100K_CONFIRMED', 'NEW_DEATHS_BY_100K',
  'NEW_RECOVERED_BY_100K', 'NEW_CONFIRMED_BY_100K', 'NEW_DEATHS', 'NEW_RECOVERED', 'NEW_CONFIRMED'];
